In [5]:
import cv2
import numpy as np
import os
from pathlib import Path

In [2]:
img = np.load('img.npy')
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
files = os.listdir('images')
print(files)
for img in files:
    img = np.load(os.path.join('images', img))
    cv2.imshow('img', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

['2025-02-26_16-38-17.npy', '2025-02-26_16-38-20.npy', '2025-02-26_16-38-19.npy']
2025-02-26_16-38-17.npy
[[[  0  11   9]
  [  1  14  12]
  [ 13  16   8]
  ...
  [109 206 132]
  [ 94 203 139]
  [ 91 200 136]]

 [[  0  12   7]
  [  1  15  10]
  [ 14  14   8]
  ...
  [104 200 128]
  [111 202 136]
  [ 92 183 117]]

 [[  2  13   5]
  [  3  14   6]
  [ 14  12   6]
  ...
  [ 53 153  90]
  [ 62 145  90]
  [ 39 122  67]]

 ...

 [[128 118 116]
  [126 116 114]
  [133 122 111]
  ...
  [127 116 117]
  [128 118 116]
  [132 122 120]]

 [[123 110 109]
  [126 113 112]
  [135 122 116]
  ...
  [124 119 114]
  [132 127 117]
  [132 127 117]]

 [[126 114 110]
  [129 117 113]
  [138 126 117]
  ...
  [125 126 118]
  [140 137 120]
  [139 136 119]]]
2025-02-26_16-38-20.npy
[[[  3   9   8]
  [  4  10   9]
  [  5  11   4]
  ...
  [ 12  22  44]
  [ 19  26  51]
  [ 21  28  53]]

 [[  3   8  11]
  [  3   8  11]
  [ 10  10   4]
  ...
  [ 11  21  41]
  [ 18  26  46]
  [ 21  29  49]]

 [[  3   6  14]
  [  3   6  14]
